name: uyg
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # 📌 Lokalizasyon desteği eklendi
    sdk: flutter
  intl: ^0.20.2  # 📌 Sürüm uyuşmazlığı çözüldü
  share_plus: ^7.2.1
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.35.3
  fl_chart: ^0.70.2
  provider: ^6.1.4
  sqflite: ^2.4.2
  timezone: ^0.10.0
  flutter_local_notifications: ^19.1.0
  path_provider: ^2.1.5
  health: ^12.2.0
  vibration: ^3.1.3
  flutter_sms: ^2.3.3
  geolocator: ^14.0.0
  contacts_service: ^0.6.3
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  percent_indicator: ^4.2.5
  printing: ^5.10.0 # Add the printing package
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/login.png
    - assets/images/aple_health.png
    - assets/images/polar.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/kalp.png